import type { GalleryImage } from "./gallery.types";

export const galleryImages: GalleryImage[] = [
  {
    id: "divine-shringar",
    title: "Divine Shringar",
    category: "Sanctum",
    image: "/images/homepage/hero-new-1.png",
    alt: "Decorated deity during temple shringar at Shri GauriShankar Baikunthnath Dham",
    featured: true,
  },
  {
    id: "gaurishankar-darshan",
    title: "GauriShankar Darshan",
    category: "Darshan",
    image: "/images/homepage/hero-new-3.png",
    alt: "Sacred GauriShankar darshan with flowers and lamps",
  },
  {
    id: "temple-view",
    title: "Temple Heritage",
    category: "Architecture",
    image: "/images/homepage/mandir-view.png",
    alt: "Temple view of Shri GauriShankar Baikunthnath Dham",
  },
  {
    id: "mahadev-alankaar",
    title: "Mahadev Alankaar",
    category: "Ritual",
    image: "/images/homepage/shankarji.png",
    alt: "Mahadev alankaar with sacred offerings",
  },
  {
    id: "festival-lights",
    title: "Festival Lights",
    category: "Festival",
    image: "/images/homepage/slide-1.jpg",
    alt: "Temple festival lights and devotional decoration",
  },
  {
    id: "sacred-aarti",
    title: "Sacred Aarti",
    category: "Aarti",
    image: "/images/homepage/slide-2.jpg",
    alt: "Sacred aarti atmosphere at the temple",
  },
  {
    id: "shivling-abhishek",
    title: "Shivling Abhishek",
    category: "Shiv Puja",
    image: "/images/shiv.jpg",
    alt: "Shivling abhishek with sacred water and flowers",
  },
  {
    id: "festival-darshan",
    title: "Festival Darshan",
    category: "Festival",
    image: "/images/homepage/slide-3.jpg",
    alt: "Festival darshan and temple decoration",
  },
  {
    id: "evening-prayers",
    title: "Evening Prayers",
    category: "Prayer",
    image: "/images/homepage/slide-4.jpg",
    alt: "Evening prayer atmosphere at the temple",
  },
  {
    id: "devotional-gathering",
    title: "Devotional Gathering",
    category: "Seva",
    image: "/images/homepage/slide-5.jpg",
    alt: "Devotional gathering and seva atmosphere",
  },
];
