import type { PanchangSlide, TempleEvent } from "./upcoming-events.types";

export const upcomingEvents: TempleEvent[] = [
  {
    title: "Mahashivratri",
    date: "February 15, 2026",
    description:
      "A night of Shiva abhishek, maha aarti, sacred chants, and devotional offerings.",
    imageSrc: "/images/homepage/hero-new-3.png",
    href: "/events/mahashivratri",
  },
  {
    title: "Shravan Somvar",
    date: "July 27, 2026",
    description:
      "Special Monday darshan and Rudrabhishek rituals throughout the holy month of Shravan.",
    imageSrc: "/images/homepage/hero-new-1.png",
    href: "/events/shravan-somvar",
  },
  {
    title: "Nag Panchami",
    date: "August 17, 2026",
    description:
      "Traditional puja, milk offering, and blessings dedicated to Nag Devta and Lord Shiva.",
    imageSrc: "/images/homepage/slide-3.jpg",
    href: "/events/nag-panchami",
  },
  {
    title: "Pradosh Vrat",
    date: "August 10, 2026",
    description:
      "Evening Shiva puja with deep daan, stotra path, and peaceful temple prayers.",
    imageSrc: "/images/homepage/slide-4.jpg",
    href: "/events/pradosh-vrat",
  },
  {
    title: "Guru Purnima",
    date: "July 29, 2026",
    description:
      "A sacred day for guru vandana, satsang, blessings, and community seva.",
    imageSrc: "/images/homepage/mandir-view.png",
    href: "/events/guru-purnima",
  },
  {
    title: "Sawan Mela",
    date: "August 3-9, 2026",
    description:
      "A week of devotional music, temple decoration, bhajan evenings, and pilgrim gatherings.",
    imageSrc: "/images/homepage/slide-5.jpg",
    href: "/events/sawan-mela",
  },
];

export const panchangSlides: PanchangSlide[] = [
  {
    label: "Mahashivratri Panchang",
    festivalName: "Mahashivratri",
    festivalDate: "February 15, 2026",
    month: "February",
    weekday: "Monday",
    dateNumber: "15",
    tithi: "Chaturdashi",
    sunrise: "5:12 AM",
    sunset: "6:21 PM",
    nakshatra: "Shravana",
    yoga: "Siddha",
    festival: "Mahashivratri",
  },
  {
    label: "Shravan Somvar Panchang",
    festivalName: "Shravan Somvar",
    festivalDate: "July 27, 2026",
    month: "July",
    weekday: "Monday",
    dateNumber: "27",
    tithi: "Ekadashi",
    sunrise: "5:12 AM",
    sunset: "6:48 PM",
    nakshatra: "Ashwini",
    yoga: "Siddhi",
    festival: "Shravan Somvar",
  },
  {
    label: "Nag Panchami Panchang",
    festivalName: "Nag Panchami",
    festivalDate: "August 17, 2026",
    month: "August",
    weekday: "Monday",
    dateNumber: "17",
    tithi: "Panchami",
    sunrise: "5:23 AM",
    sunset: "6:32 PM",
    nakshatra: "Anuradha",
    yoga: "Shubha",
    festival: "Nag Panchami",
  },
  {
    label: "Pradosh Vrat Panchang",
    festivalName: "Pradosh Vrat",
    festivalDate: "August 10, 2026",
    month: "August",
    weekday: "Monday",
    dateNumber: "10",
    tithi: "Trayodashi",
    sunrise: "5:20 AM",
    sunset: "6:38 PM",
    nakshatra: "Mrigashira",
    yoga: "Saubhagya",
    festival: "Pradosh Vrat",
  },
  {
    label: "Guru Purnima Panchang",
    festivalName: "Guru Purnima",
    festivalDate: "July 29, 2026",
    month: "July",
    weekday: "Wednesday",
    dateNumber: "29",
    tithi: "Purnima",
    sunrise: "5:14 AM",
    sunset: "6:46 PM",
    nakshatra: "Uttara Ashadha",
    yoga: "Vishkambha",
    festival: "Guru Purnima",
  },
  {
    label: "Sawan Mela Panchang",
    festivalName: "Sawan Mela",
    festivalDate: "August 3-9, 2026",
    month: "August",
    weekday: "Monday",
    dateNumber: "03",
    tithi: "Shukla Paksha",
    sunrise: "5:16 AM",
    sunset: "6:43 PM",
    nakshatra: "Rohini",
    yoga: "Dhriti",
    festival: "Sawan Mela",
  },
];
