import type { PanchangSlide, TempleEvent } from "./upcoming-events.types";

export const upcomingEvents: TempleEvent[] = [
  {
    title: "Mahashivratri",
    date: "Date to be announced",
    description:
      "A night of Shiva abhishek, aarti, sacred chants, and devotional offerings.",
    imageSrc: "/images/homepage/hero-new-3.png",
    href: "/events/mahashivratri",
  },
  {
    title: "Shravan Somvar",
    date: "During Shravan",
    description:
      "Special Monday darshan and Rudrabhishek rituals throughout the holy month of Shravan.",
    imageSrc: "/images/homepage/hero-new-1.png",
    href: "/events/shravan-somvar",
  },
  {
    title: "Nag Panchami",
    date: "Date to be announced",
    description:
      "Traditional puja, milk offering, and blessings dedicated to Nag Devta and Lord Shiva.",
    imageSrc: "/images/homepage/slide-3.jpg",
    href: "/events/nag-panchami",
  },
  {
    title: "Pradosh Vrat",
    date: "As per Panchang",
    description:
      "Evening Shiva puja with deep daan, stotra path, and peaceful temple prayers.",
    imageSrc: "/images/homepage/slide-4.jpg",
    href: "/events/pradosh-vrat",
  },
  {
    title: "Guru Purnima",
    date: "Date to be announced",
    description:
      "A sacred day for guru vandana, satsang, blessings, and community seva.",
    imageSrc: "/images/homepage/mandir-view.png",
    href: "/events/guru-purnima",
  },
  {
    title: "Sawan Mela",
    date: "Schedule to be announced",
    description:
      "A week of devotional music, temple decoration, bhajan evenings, and pilgrim gatherings.",
    imageSrc: "/images/homepage/slide-5.jpg",
    href: "/events/sawan-mela",
  },
];

export const panchangSlides: PanchangSlide[] = [
  {
    label: "Mahashivratri Panchang",
    festivalName: "Mahashivratri",
    festivalDate: "Date to be announced",
    month: "Panchang",
    weekday: "TBD",
    dateNumber: "--",
    tithi: "Chaturdashi",
    sunrise: "Local timing",
    sunset: "Local timing",
    nakshatra: "To be announced",
    yoga: "To be announced",
    festival: "Mahashivratri",
  },
  {
    label: "Shravan Somvar Panchang",
    festivalName: "Shravan Somvar",
    festivalDate: "During Shravan",
    month: "Shravan",
    weekday: "Monday",
    dateNumber: "--",
    tithi: "As per Panchang",
    sunrise: "Local timing",
    sunset: "Local timing",
    nakshatra: "To be announced",
    yoga: "To be announced",
    festival: "Shravan Somvar",
  },
  {
    label: "Nag Panchami Panchang",
    festivalName: "Nag Panchami",
    festivalDate: "Date to be announced",
    month: "Panchang",
    weekday: "TBD",
    dateNumber: "--",
    tithi: "Panchami",
    sunrise: "Local timing",
    sunset: "Local timing",
    nakshatra: "To be announced",
    yoga: "To be announced",
    festival: "Nag Panchami",
  },
  {
    label: "Pradosh Vrat Panchang",
    festivalName: "Pradosh Vrat",
    festivalDate: "As per Panchang",
    month: "Panchang",
    weekday: "TBD",
    dateNumber: "--",
    tithi: "Trayodashi",
    sunrise: "Local timing",
    sunset: "Local timing",
    nakshatra: "To be announced",
    yoga: "To be announced",
    festival: "Pradosh Vrat",
  },
  {
    label: "Guru Purnima Panchang",
    festivalName: "Guru Purnima",
    festivalDate: "Date to be announced",
    month: "Panchang",
    weekday: "TBD",
    dateNumber: "--",
    tithi: "Purnima",
    sunrise: "Local timing",
    sunset: "Local timing",
    nakshatra: "To be announced",
    yoga: "To be announced",
    festival: "Guru Purnima",
  },
  {
    label: "Sawan Mela Panchang",
    festivalName: "Sawan Mela",
    festivalDate: "Schedule to be announced",
    month: "Shravan",
    weekday: "TBD",
    dateNumber: "--",
    tithi: "As per Panchang",
    sunrise: "Local timing",
    sunset: "Local timing",
    nakshatra: "To be announced",
    yoga: "To be announced",
    festival: "Sawan Mela",
  },
];
